import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/project_model.dart';
import '../services/firestore_service.dart';

// State definition for Add Project Form
class ProjectAddState {
  final bool isLoading;
  final String? errorMessage;
  final DateTime dueDate;
  final String status;
  final String paymentStatus;

  ProjectAddState({
    this.isLoading = false,
    this.errorMessage,
    required this.dueDate,
    this.status = 'In Progress',
    this.paymentStatus = 'Unpaid',
  });

  ProjectAddState copyWith({
    bool? isLoading,
    String? errorMessage,
    DateTime? dueDate,
    String? status,
    String? paymentStatus,
  }) {
    return ProjectAddState(
      isLoading: isLoading ?? this.isLoading,
      errorMessage: errorMessage,
      dueDate: dueDate ?? this.dueDate,
      status: status ?? this.status,
      paymentStatus: paymentStatus ?? this.paymentStatus,
    );
  }
}

// Controller for Add Project view
class ProjectAddController extends Notifier<ProjectAddState> {
  @override
  ProjectAddState build() {
    return ProjectAddState(
      dueDate: DateTime.now().add(const Duration(days: 14)),
    );
  }

  FirestoreService get _service => ref.read(firestoreServiceProvider);

  void selectDate(DateTime date) {
    state = state.copyWith(dueDate: date);
  }

  void selectStatus(String status) {
    state = state.copyWith(status: status);
  }

  void selectPaymentStatus(String paymentStatus) {
    state = state.copyWith(paymentStatus: paymentStatus);
  }

  Future<bool> saveProject({
    required String name,
    required String clientName,
    required double budget,
    required String description,
  }) async {
    if (name.trim().isEmpty || clientName.trim().isEmpty || budget <= 0) {
      state = state.copyWith(errorMessage: 'Mohon isi semua kolom yang wajib dengan benar.');
      return false;
    }

    state = state.copyWith(isLoading: true, errorMessage: null);

    try {
      final project = Project(
        id: '', // Will be generated by Firestore
        name: name.trim(),
        clientName: clientName.trim(),
        budget: budget,
        dueDate: state.dueDate,
        status: state.status,
        paymentStatus: state.paymentStatus,
        description: description.trim(),
        createdAt: DateTime.now(),
      );

      await _service.addProject(project);
      state = state.copyWith(isLoading: false);
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, errorMessage: 'Gagal menyimpan ke Firestore: $e');
      return false;
    }
  }
}

// Controller for Project List & Dashboard interactions
class ProjectListController {
  final Ref _ref;

  ProjectListController(this._ref);

  FirestoreService get _service => _ref.read(firestoreServiceProvider);

  Future<void> updateProjectStatus(String id, String status) async {
    await _service.updateProjectStatus(id, status);
  }

  Future<void> updatePaymentStatus(String id, String paymentStatus) async {
    await _service.updatePaymentStatus(id, paymentStatus);
  }

  Future<void> deleteProject(String id) async {
    await _service.deleteProject(id);
  }

  Future<void> updateProject(Project project) async {
    await _service.updateProject(project);
  }
}

// Providers for Controllers
final projectAddControllerProvider =
    NotifierProvider<ProjectAddController, ProjectAddState>(() {
  return ProjectAddController();
});

final projectListControllerProvider = Provider<ProjectListController>((ref) {
  return ProjectListController(ref);
});

final projectDetailProvider = Provider.family<AsyncValue<Project>, String>((ref, id) {
  final projectsAsync = ref.watch(projectsStreamProvider);
  return projectsAsync.whenData((list) => list.firstWhere(
        (p) => p.id == id,
        orElse: () => throw Exception('Proyek tidak ditemukan'),
      ));
});
